// Generated by CoffeeScript 1.6.3
(function() {
  var Range, applyToShareJS, cursorToRange, rangeToCursor,
    __hasProp = {}.hasOwnProperty;

  Range = require("ace/range").Range;

  rangeToCursor = function(editorDoc, range) {
    return [editorDoc.positionToIndex(range.start), editorDoc.positionToIndex(range.end)];
  };

  cursorToRange = function(editorDoc, cursor) {
    var end, range, start;
    if (!(cursor instanceof Array)) {
      cursor = [cursor, cursor];
    }
    start = editorDoc.indexToPosition(cursor[0]);
    end = editorDoc.indexToPosition(cursor[1]);
    range = Range.fromPoints(start, end);
    range.cursor = end;
    return range;
  };

  applyToShareJS = function(editorDoc, delta, doc) {
    var pos, text;
    pos = rangeToCursor(editorDoc, delta.range)[0];
    switch (delta.action) {
      case 'insertText':
        doc.insert(pos, delta.text);
        break;
      case 'removeText':
        doc.del(pos, delta.text.length);
        break;
      case 'insertLines':
        text = delta.lines.join('\n') + '\n';
        doc.insert(pos, text);
        break;
      case 'removeLines':
        text = delta.lines.join('\n') + '\n';
        doc.del(pos, text.length);
        break;
      default:
        throw new Error("unknown action: " + delta.action);
    }
  };

  window.sharejs.extendDoc('attach_ace', function(editor, keepEditorContents) {
    var check, cursorListener, doc, docListener, editorDoc, editorListener, offsetToPos, suppress, updateCursors;
    this.editorAttached = true;
    if (!this.provides['text']) {
      throw new Error('Only text documents can be attached to ace');
    }
    doc = this;
    editorDoc = editor.getSession().getDocument();
    editorDoc.setNewLineMode('unix');
    check = function() {
      var _this = this;
      return window.setTimeout(function() {
        var editorText, otText, suppress;
        editorText = editorDoc.getValue();
        otText = doc.getText();
        if (editorText !== otText) {
          console.error("editor: " + editorText);
          console.error("ot:     " + otText);
          suppress = true;
          editorDoc.setValue(otText);
          suppress = false;
          return doc.emit("warn", "OT/editor mismatch\nOT: " + otText + "\neditor: " + editorText);
        }
      }, 0);
    };
    if (keepEditorContents) {
      doc.del(0, doc.getText().length);
      doc.insert(0, editorDoc.getValue());
    } else {
      editorDoc.setValue(doc.getText());
    }
    check();
    suppress = false;
    updateCursors = function() {
      var colors, cursor, cursorElement, cursorLayer, i, marker, range, ranges, sessionId, _i, _j, _len, _len1, _ref, _ref1, _ref2, _results;
      if (this.markers == null) {
        this.markers = [];
      }
      _ref = this.markers;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        marker = _ref[_i];
        editor.session.removeMarker(marker);
      }
      ranges = [];
      _ref1 = this.cursors;
      for (sessionId in _ref1) {
        if (!__hasProp.call(_ref1, sessionId)) continue;
        cursor = _ref1[sessionId];
        range = cursorToRange(editorDoc, cursor);
        this.markers.push(editor.session.addMarker(range, "foreign_selection ace_selection", "line"));
        if (range) {
          ranges.push(range);
        }
      }
      ranges.push({
        cursor: null
      });
      editor.session.$selectionMarkers = ranges;
      cursorLayer = editor.renderer.$cursorLayer;
      cursorLayer.update(editor.renderer.layerConfig);
      colors = ["Brown", "DarkCyan", "DarkGreen", "DarkRed", "DarkSeaGreen", "MediumSlateBlue"];
      _ref2 = cursorLayer.cursors.slice(1);
      _results = [];
      for (i = _j = 0, _len1 = _ref2.length; _j < _len1; i = ++_j) {
        cursorElement = _ref2[i];
        _results.push(cursorElement.style.borderColor = colors[i % 6]);
      }
      return _results;
    };
    this.on("cursors", updateCursors);
    editorListener = function(change) {
      if (suppress) {
        return;
      }
      applyToShareJS(editorDoc, change.data, doc);
      updateCursors.call(doc);
      return check();
    };
    cursorListener = function(change) {
      var cursor;
      cursor = rangeToCursor(editorDoc, editor.getSelectionRange());
      return doc.setCursor(cursor);
    };
    editorDoc.on('change', editorListener);
    editor.on("changeSelection", cursorListener);
    docListener = function(op) {
      suppress = true;
      applyToDoc(editorDoc, op);
      suppress = false;
      return check();
    };
    offsetToPos = function(offset) {
      return editorDoc.indexToPosition(offset);
    };
    doc.on('insert', function(pos, text) {
      suppress = true;
      editorDoc.insert(offsetToPos(pos), text);
      suppress = false;
      return check();
    });
    doc.on('delete', function(pos, text) {
      var range;
      suppress = true;
      range = Range.fromPoints(offsetToPos(pos), offsetToPos(pos + text.length));
      editorDoc.remove(range);
      suppress = false;
      return check();
    });
    doc.detach_ace = function() {
      this.editorAttached = false;
      doc.removeListener('remoteop', docListener);
      doc.removeListener('cursors', updateCursors);
      editorDoc.removeListener('change', editorListener);
      editor.removeListener('changeSelection', cursorListener);
      return delete doc.detach_ace;
    };
  });

}).call(this);
